@hostname = http://localhost
@port = 8080
@host = {{hostname}}:{{port}}




POST {{host}}/Passwords/reset
Content-Type: application/json

{
    "Email" : "thechanman.potato@gmail.com"
}

###

POST {{host}}/Passwords/resetValidate
Content-Type: application/json

{
    "Email" : "thechanman.potato@gmail.com",
    "Password" : "123",
    "Token" : "3d0a8764e24af47c60c9b6b24d4c8db408244ec6c20ac9354282fc5b54ac0401"
}